config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'locations/find_address'
  resources :categories, only: %i[show] do
    member do
      get :search
    end
  end
  resources :orders, only: %i[index destroy] do
    collection do
      get :cart
      get :user
      get :dashboard
      delete :empty_cart
    end
    member do
      patch :add_item
      patch :less_item
      patch :dispached
    end
  end
  resources :shops do
    collection do
      get :search
      get :cart
    end
    resources :products do
      collection do
        get :search
        get :search_range_price
      end
      resources :orders, only: %i[create]
    end
  end
  resources :billings, only: [] do
    collection do
      post 'pre_pay'
      get 'execute'
    end
  end
  resources :payout_batches, only: %i[create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'locations/find_address'
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy
  has_many_attached :images
  has_many :orders, dependent: :destroy

  def self.created_by_day
    group_by_day(:created_at).count
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy]
  load_and_authorize_resource
  def index
    @shops = Shop.all
    @category = Category.all
  end

  def new
    @shop = Shop.new
    respond_to :js
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user = current_user
    if @shop.save
      redirect_to root_path, notice: 'Tienda Creada Con Exito'
    else
      redirect_to root_path, alert: 'Error Tienda no Creada Intente Nuevamente'
    end
  end

  def show
    @products = Product.where(shop_id: @shop.id)
    @order = Order.new
    @categories = Category.all
  end

  def edit
    respond_to :js
  end

  def update
    @shop.update(shop_params)
    if @shop.save
      respond_to :js
    else
      redirect_to root_path, alert: 'Error al Actualizar la Tienda'
    end
  end

  def destroy
    @shop.destroy
    respond_to :js
  end

  def search
    parameters = params[:search]
    if parameters.blank?
      @shops = Shop.all
      respond_to :js
    elsif parameters.nil?
      @shops = Shop.all
      respond_to :js
    else
      @shops = Shop.where('name LIKE ?',"%#{parameters}%")
      respond_to :js
    end
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :description, :user_id, images: [])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |f| %>
        <div class="field">
                <%= f.label :Nombre_Tienda %>
                <%= f.text_field :name, class: 'form-control'%>
        </div>
        <%= f.hidden_field :user_id, value: current_user.id %>

        <div class="field">
                <%= f.label :Descripcion %>
                <%= f.text_area :description, class: 'form-control'%>
        </div>
        
        <div class="field">
                <%= f.label :Imagenes %>
                <%= f.file_field :images, multiple: true %>
        </div>
        <%= f.submit 'Crear Tienda', class: 'btn btn-success' %>
<% end %>

app/views/shops/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">

            </div>
          </div>
        </div>
      </div>

app/views/shops/_search.html.erb
<%= form_with(model: shop) do |f| %>
        <%= f.label :Buscar %>
        <%= f.text_field :search , class: 'form-control'%>
<% end %>

app/views/shops/_shop.html.erb
    <div class="col col-md-3">
        <figure class="card card-product">
          <div class="img-wrap"> 
              <% if shop.images.attached? %>
              <a href="<%= shop_path(shop)%>"><%= image_tag(shop.images.second.variant(resize: '400x266'), class: 'img-top')%></a>
            <% end %>
            <a class="btn-overlay" href="#">
          </div>
          <figcaption class="info-wrap">
            <a href="#" class="title"><%= shop.name %></a>
            <div class="action-wrap">
              </div> <!-- price-wrap.// -->
          </figcaption>
        </figure> <!-- card // -->
      </div>

app/views/shops/create.js.erb
$('.shops').append("<%= j render @shop %>");
$('#exampleModal').modal('hide');
$('#shop_name').text('<%= @shop.name%>')

app/views/shops/destroy.html.erb
<h1>Shops#destroy</h1>
<p>Find me in app/views/shops/destroy.html.erb</p>

app/views/shops/destroy.js.erb
$('#<%= @shop.id%>').fadeOut();
location.href = "<%= root_path %>";

app/views/shops/edit.js.erb
$('.modal-body').html("<%= j render 'form', shop: @shop %>")
$('.modal-title').text('Editar Tienda');
$('#exampleModal').modal('show');

app/views/shops/index.html.erb
<section class="text-white text-center">
  <div class="container d-flex flex-column"  style="min-height:80vh;">

  <div class="row mt-auto">
      <div class="col-lg-8 col-sm-12 text-center mx-auto">
          <h1 class="display-4 mb-3">Basthor Marketplace</h1>
      </div>
  </div>
  <div class="row">
      <div class="col-lg-9 col-md-8 col-sm-12 mx-auto text-center">

                <input class="form-control form-control-lg" placeholder="Busca tu Tienda" id="search" type="text">

          <ul class="list-inline my-5">
              <li class="list-inline-item">
                  <a class="h4 text-light p-2" href="#">
                      <i class="fab fa-twitter"></i>
                  </a>
              </li>
              <li class="list-inline-item">
                  <a class="h4 text-light p-2" href="#">
                      <i class="fab fa-facebook"></i>
                  </a>
              </li>
              <li class="list-inline-item">
                  <a class="h4 text-light p-2" href="#">
                      <i class="fab fa-dribbble"></i>
                  </a>
              </li>
              <li class="list-inline-item">
                  <a class="h4 text-light p-2" href="#">
                      <i class="fab fa-instagram"></i>
                  </a>
              </li>
          </ul>
      </div> <!-- col.// -->
  </div> <!-- row.// -->

  </div>
  </section>
  <div class="container">
  <section class="section-content padding-y">
    <header class="section-heading">
        <h1 class="my-4"> <span class="badge badge-warning">Tiendas</span></h1>
    </header><!-- sect-heading -->

            <br>
            <%= link_to "Pagar Proveedores", payout_batches_path, method: :post, class: 'btn btn-success' %>
    <div class="row" id= "shops">
        <% @shops.each do |shop| %>
        <div class="col col-md-3" id="<%= shop.id%>">
        <figure class="card card-product">
          <div class="img-wrap">
              <% if shop.images.attached? %>
              <a href="<%= shop_path(shop)%>"><%= image_tag(shop.images.second.variant(resize: '400x266'), class: 'img-top')%></a>
            <% end %>
            <a class="btn-overlay" href="#">
          </div>
          <figcaption class="info-wrap">
            <a href="#" class="title"><%= shop.name %></a>
            <div class="action-wrap">
              </div> <!-- price-wrap.// -->
          </figcaption>
        </figure> <!-- card // -->
      </div>
        <% end %>
    </div>
  </div>
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


              <%= render  "modal" %>


              <script>
                  $('#search').keyup(function(){
                    $.ajax({
                      type: "GET",
                      url: "<%= search_shops_path%>",
                      data: {search: $('#search').val()},
                      success: function (response) {

                      }
                });
                  });
                </script>

app/views/shops/new.js.erb
$('.modal-title').text('Crear Tienda');
$('#exampleModal').modal('show');
$('.modal-body').html("<%= j render 'form', shop: @shop%>")

app/views/shops/search.js.erb
$('#shops').html("<%= j render @shops %>");

app/views/shops/show.html.erb
<br>
<br>
<br>
<div class="container">
    <section class="section-pagetop">
        <div class="container clearfix">
          <%= image_tag(@shop.images.second.variant(resize: '200x200'),class: 'd-block img-fluid') %>
          <h2><span class="badge badge-success"><%= @shop.name %></span></h2>
        </div> <!-- container //  -->
        </section>
    <ul class="list-group list-group-horizontal">
        <% if current_user.provider? && @shop.user_id == current_user.id %>
          <li class="list-group-item"><%= link_to "Crear Producto",new_shop_product_path(@shop), data:{ remote: true} %></li>
         <% end %>

      </ul>     <br>
                <br>
                <div class="row">

                  <div class="col-lg-3">
                        <div class="card card-filter">
                          <article class="card-group-item">
                            <header class="card-header">
                              <a class="" aria-expanded="true" href="#" data-toggle="collapse" data-target="#collapse22">
                                <i class="icon-action fa fa-chevron-down"></i>
                                <h6 class="title"> Por Nombre</h6>
                              </a>
                            </header>
                            <div style="" class="filter-content collapse show" id="collapse22">
                              <div class="card-body">
                                <form class="pb-3">
                                <div class="input-group">
                                  <input class="form-control" placeholder="Search" id="search" type="text">
                                  <div class="input-group-append">
                                    <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                                  </div>
                                </div>
                                </form> 
                              </div> <!-- card-body.// -->
                            </div> <!-- collapse .// -->
                          </article> <!-- card-group-item.// -->

                          <article class="card-group-item">
                            <header class="card-header">
                              <a class="" aria-expanded="true" href="#" data-toggle="collapse" data-target="#collapse22">
                                <i class="icon-action fa fa-chevron-down"></i>
                                <h6 class="title"> Por Categoria</h6>
                              </a>
                            </header>
                            <div style="" class="filter-content collapse show" id="collapse22">
                              <div class="card-body">
                                <form class="pb-3">
                                <div class="input-group">
                                  <div class="input-group-append">
                                    
                                  </div>
                                </div>
                                </form>
                        
                                <ul class="list-unstyled list-lg">
                                   <% @categories.each do |category| %>
                                   <li><a href="<%=category_path(category) %>"><%= category.name %> <span class="float-right badge badge-warning round"><%= category.products.count %></span> </a></li>
                                  <% end %>
                                </ul>  
                              </div> <!-- card-body.// -->
                            </div> <!-- collapse .// -->
                          </article> <!-- card-group-item.// -->
                          <article class="card-group-item">
                            <header class="card-header">
                              <a href="#" data-toggle="collapse" data-target="#collapse33">
                                <i class="icon-action fa fa-chevron-down"></i>
                                <h6 class="title">By Price  </h6>
                              </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse33">
                              <div class="card-body">
                                <input type="range" class="custom-range" min="0" max="10000" name="" id="range_price">
                                <div class="form-row">
                                <div class="form-group col-md-6">
                                  <label>Min</label>
                                  <input class="form-control" placeholder="$0" id="min">
                                </div>
                                <div class="form-group text-right col-md-6">
                                  <label>Max</label>
                                  <input class="form-control" placeholder="$1,0000" id="max">
                                </div>
                                </div> <!-- form-row.// -->
                              </div> <!-- card-body.// -->
                            </div> <!-- collapse .// -->
                          </article> <!-- card-group-item.// -->
                        </div> <!-- card.// -->
                        
                      

                  </div>
                  <!-- /.col-lg-3 -->

                  <div class="col-lg-9">

                    <!--<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                      <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                      </ol>
                      <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                          <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                        </div>
                        <div class="carousel-item">
                          <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                          <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                        </div>
                      </div>
                      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>-->
                    <br><br>
                    <div class="row" id='products'>
                          <% @products.each do |product| %>
                          <article class="card card-product" id="<%= product.id%>">
                              <div class="card-body">
                              <div class="row">
                                <aside class="col-sm-3">
                                  <div class="img-wrap"><a href="<%= shop_product_path(@shop, product)%>"><%= image_tag(product.image.variant(resize: '800x800'),class: "card-img-top") %></a></div>
                                </aside> <!-- col.// -->
                                <article class="col-sm-6">
                                    <h4 class="title"><%= product.name %></h4>
                                    <div class="rating-wrap  mb-2">
                                      <ul class="rating-stars">
                                        <li style="width:80%" class="stars-active"> 
                                          <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                                          <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                                          <i class="fa fa-star"></i> 
                                        </li>
                                        <li>
                                          <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                                          <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                                          <i class="fa fa-star"></i> 
                                        </li>
                                      </ul>
                                    </div> <!-- rating-wrap.// -->
                                    <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, Lorem ipsum dolor sit amet, consectetuer adipiscing elit, Ut wisi enim ad minim veniam </p>
                                    <dl class="dlist-align">
                                    </dl>  <!-- item-property-hor .// -->
                                    <dl class="dlist-align">
                                      <dt>Categorias</dt>
                                        <% product.categories.each do |category| %>
                                        <dd><span class="badge badge-success"><%= category.name %></span></dd>
                                        <% end %>
                                        </dl>  <!-- item-property-hor .// -->
                                  
                                </article> <!-- col.// -->
                                <aside class="col-sm-3 border-left">
                                  <div class="action-wrap">
                                    <div class="price-wrap h4">
                                      <span class="price"><%= product.price %></span>	
                 
                                    </div> <!-- info-price-detail // -->
                                    <p class="text-success">Free shipping</p>
                                    <br>
                                    <p>
                                        <% if can? :update, Product %>
                                        <%= link_to  "Editar", edit_shop_product_path(@shop,product), class: 'btn btn-info', data:{remote: true}  %>
                                        <%= link_to  "Eliminar",shop_product_path(@shop, product), class: 'btn btn-danger', data:{ confirm: 'Estas Seguro?', remote: true}, method: :delete %>
          
                                        <% else %>
                                          <% if product.stock == 0 %>
                                                    <button type="button" class="btn btn-info" name="button">Producto Agotado</button>
                                              <%else %>
                                                <%= link_to(shop_product_orders_path(product.shop,product),data: {remote: true}, method: :post) do  %>
                                                 <button class="btn btn-primary">Agregar al Carrito <i class="fas fa-shopping-cart"></i></button>

                                                <% end %>
                                                <%end%>
                                        <% end %>
                                    </p>
                                  </div> <!-- action-wrap.// -->
                                </aside> <!-- col.// -->
                              </div> <!-- row.// -->
                              </div> <!-- card-body .// -->
                            </article> <!-- card product .// -->


                      <% end %>

                    </div>
                    <!-- /.row -->

                  </div>
                  <!-- /.col-lg-9 -->

                </div>
                <!-- /.row -->

              </div>
              <!-- /.container -->

              <%= render  "modal" %>

              <script>
                  $('#search').keyup(function(){
                    $.ajax({
                      type: "GET",
                      url: "<%= search_shop_products_path(@shop)%>",
                      data: {search: $('#search').val()},
                      success: function (response) {

                      }
                });
                  });
                </script>

                <script>
                    $("#range_price").on('mouseup',function () {                    
                    
                      $.ajax({
                        type: "GET",
                        url: "<%= search_range_price_shop_products_path(@shop) %>",
                        data: {search: $('#range_price').val(),
                               min: $('#min').val(),
                               max: $('#max').val()},
                        success: function (response) {
                            console.log(response)
                        }
                  });
                   });

                </script>

                

app/views/shops/update.html.erb
<h1>Shops#update</h1>
<p>Find me in app/views/shops/update.html.erb</p>

app/views/shops/update.js.erb
$("#<%=@shop.id%>").replaceWith("<%= j render @shop %>");
$('#shop_name').text('<%= @shop.name%>');
$("#exampleModal").modal('hide');