config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'locations/find_address'
  resources :categories, only: %i[show] do
    member do
      get :search
    end
  end
  resources :orders, only: %i[index destroy] do
    collection do
      get :cart
      get :user
      get :dashboard
      delete :empty_cart
    end
    member do
      patch :add_item
      patch :less_item
      patch :dispached
    end
  end
  resources :shops do
    collection do
      get :search
      get :cart
    end
    resources :products do
      collection do
        get :search
        get :search_range_price
      end
      resources :orders, only: %i[create]
    end
  end
  resources :billings, only: [] do
    collection do
      post 'pre_pay'
      get 'execute'
    end
  end
  resources :payout_batches, only: %i[create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'locations/find_address'
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partial/_barchart.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", "chartkick" %>
<%=  bar_chart Shop.created_by_day %>

app/views/partial/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark fixed-bottom">
                <div class="container">
                  <p class="m-0 text-center text-white"><span class="badge badge-success">Basthor</span> Copyright &copy; Basthor 2019</p>
                </div>
                <!-- /.container -->
              </footer>

app/views/partial/_linechart.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", "chartkick" %>
<%=  line_chart Order.created_by_day %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="#">Basthor </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="<%= root_path%>">Inicio
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="far fa-user"></i>
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%if current_user.client?%>
         <a class="dropdown-item" href="<%=user_orders_path%>">Mis Pedidos <i class="fas fa-shopping-bag"></i></a>
         <a class="dropdown-item" data-method="DELETE" href="<%= destroy_user_session_path%>">Cerrar Sesion <i class="fas fa-user"></i></a>
         <% else %>
          <% if current_user.shop == nil %>
         <a class="dropdown-item" href="#">Ordenes <i class="fas fa-truck"></i></a>
             <a class="dropdown-item" href="#">Mi Tienda <i class="fas fa-store "></i></a>
              <a class="dropdown-item" href="#">DashBoard <i class="fas fa-chart-line"></i></a>
         <%else%>
         <a class="dropdown-item" href="<%= orders_path%>">Ordenes <i class="fas fa-truck"></i></a>
            <a class="dropdown-item" href="<%= shop_path(current_user.shop)%>">Mi Tienda <i class="fas fa-store "></i></a>
            <a class="dropdown-item" href="<%=  dashboard_orders_path %>">DashBoard <i class="fas fa-chart-line"></i></a>
         <% end %>
         <div class="dropdown-divider"></div>
         <a class="dropdown-item" data-method="DELETE" href="<%= destroy_user_session_path%>">Cerrar Sesion <i class="fas fa-user"></i></a>
         <% end %>
       </div>
     </li> 
     <li class="nav-item">
        <a class="nav-link" data-remote="true" href="<%= new_shop_path %>"><i class="fas fa-store "></i></a>
     </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= cart_orders_path%>"><i class="fas fa-shopping-cart"></i> <span class="badge badge-warning" id="cart"><%= current_user.cart.count %></span></a>
                  </li>
              <% else %>
              <li class="nav-item">
                  <a class="nav-link" href="<%=new_user_session_path%>">Inciar Sesion</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%=new_user_registration_path%>">Crear Cuenta</a>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>