config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'locations/find_address'
  resources :categories, only: %i[show] do
    member do
      get :search
    end
  end
  resources :orders, only: %i[index destroy] do
    collection do
      get :cart
      get :user
      get :dashboard
      delete :empty_cart
    end
    member do
      patch :add_item
      patch :less_item
      patch :dispached
    end
  end
  resources :shops do
    collection do
      get :search
      get :cart
    end
    resources :products do
      collection do
        get :search
        get :search_range_price
      end
      resources :orders, only: %i[create]
    end
  end
  resources :billings, only: [] do
    collection do
      post 'pre_pay'
      get 'execute'
    end
  end
  resources :payout_batches, only: %i[create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'locations/find_address'
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :shop
  belongs_to :billing, optional: true

  def self.paid_and_dispached
    where(paid: true).where(dispached: true)
  end

  def self.created_by_day
  	group_by_day(:created_at).count
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders_per_user = current_user.shop.orders.where(paid: true).where(dispached: false).group_by{|order| order.user.id}
  end

  def create
    @order = Order.find_or_initialize_by(
      product_id: params[:product_id],
      shop_id: params[:shop_id],
      user_id: current_user.id,
      paid: false,
      completed: false,
      dispached: false)
    @order.price = @order.product.price
    @order.quantity += 1
    respond_to :js if @order.save
  end

  def cart
    @orders = current_user.orders.where(paid: false)
    @total = @orders.map { |order| order.price * order.quantity }.sum
  end

  def destroy
    @orders = current_user.orders.where(paid: false)
    @order = Order.find(params[:id])
    @order.destroy
    @total = @orders.map { |order| order.price * order.quantity }.sum
    respond_to :js if @order.save
  end

  def empty_cart
    @orders = current_user.orders.where(paid: false)
    @orders.destroy_all
    redirect_to cart_orders_path, notice: 'Carro vaciado con éxito!'
  end
  def add_item
    @orders = current_user.orders.where(paid: false)
    @order = Order.find(params[:id])
    @order.quantity += 1
    @order.save if @order.changed?
    @total = @orders.map { |order| order.price * order.quantity }.sum
    respond_to :js
  end

  def less_item
    @orders = current_user.orders.where(paid: false)
    @order = Order.find(params[:id])
    @order.quantity -= 1 if @order.quantity > 1
    @order.save if @order.changed?
    @total = @orders.map { |order| order.price * order.quantity }.sum
    respond_to :js
  end

  def dispached
    user = User.find(params[:id])
    orders_per_user = user.orders.where(paid: true).where(dispached: false)
    orders_per_user.update_all(dispached: true)
    puts 'Orden de compra del usuario ha sido despachada en su totalidad'
    UserMailer.new_pack_off(user, orders_per_user).deliver
    redirect_to orders_path
  end

  def user
    @orders_user = current_user.orders.where(paid: true)
    # estado de la orden... cambiar color del tr
  end
  def dashboard
    @orders = current_user.shop.orders.where(paid: true).where(dispached: true).group_by_month{|order| order.created_at}
    @count_products_shop = current_user.shop.products.count
    @orders_shop = current_user.shop.orders.count
    @orders_dispached_shop = current_user.shop.orders.where(paid: true).where(dispached: true).count
    @orders_not_dispached_shop = current_user.shop.orders.where(paid: true).where(dispached: false).count
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/add_item.js.erb
$('#item_quantity_<%=@order.id%>').html("<%= @order.quantity%>")
$('#total').html("<i class='fas fa-money-bill-alt'></i> <%= @total%>");

app/views/orders/cart.html.erb
<br>
<br>
<br>
<br>
<div class="container">
                <table id="cart" class="table table-dark">
                  <thead>
                    <tr>
                      <th style="width:50%">Producto</th>
                      <th style="width:10%">Precio</th>
                      <th style="width:8%">Cantidad</th>
                      <th style="width:22%" class="text-center">Subtotal</th>
                      <th style="width:10%"></th>
                    </tr>
                  </thead>
                  <tbody>
        <% @orders.each do |order| %>
                        

                    <tr id="<%= order.id%>">
                      <td data-th="Product">
                        <div class="row">
                          <div class="col-sm-2 hidden-xs"><%= image_tag(order.product.image.variant(resize: '150x150'),class:"img-responsive") %></div>
                          <div class="col-sm-10">
                            <h4 class="nomargin"></h4>
                          </div>
                        </div>
                      </td>
                      <td data-th="Price"><%= order.product.price %></td>
                      <td data-th="Quantity">
                        <%= link_to(less_item_order_path(order), method: :patch,data:{remote: true}) do%>
                          <i class="fas fa-minus-square"></i>
                        <% end %>
                        
                        <span class="badge badge-warning" id="item_quantity_<%= order.id%>"><%= order.quantity%> </span><%= link_to(add_item_order_path(order), method: :patch, data: {remote: true}) do %>
                          <i class="fas fa-plus-square"></i>
                        <% end %>
                      </td>
                      <td data-th="Subtotal" class="text-center"><%= order.quantity * order.product.price%></td>
                      <td class="actions" data-th="">
                        <%= link_to(order_path(order), data:{remote: true, confirm: 'Estas Seguro?'}, method: :delete, class:'btn btn-danger') do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td></td>
                      <td><%= link_to(empty_cart_orders_path,method: :delete, class: 'btn btn-danger') do%>
                        <i class="fas fa-backspace"></i>
                      <% end %>
                      </td>
                      <td colspan="1" class="hidden-xs"></td>
                      <td class="hidden-xs text-center"><strong id="total"><i class="fas fa-money-bill-alt"></i> <%= @total %></strong></td>
                      <td><%= link_to  '<i class="fab fa-paypal"></i>'.html_safe, pre_pay_billings_path, method: :post,data:{remote: true},class:"btn btn-success btn-block"  %></td>
                    </tr>
                  </tfoot>
                </table>
              </div>

app/views/orders/create.js.erb
$('#cart').text('<%= current_user.cart.count%>');
$('#alerts').html('<p class="alert alert-success">Producto Agregado Correctamente al Carro</p>');       

app/views/orders/dashboard.html.erb
<div class="container">
<h1><span class="badge badge-warning">Dashboard</span></h1>
<br>
<br>
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Mis Productos</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @count_products_shop %></div>
            </div>
            <div class="col-auto">
              <i class="fas fa-box fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Ordenes Recibidas</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @orders_shop %></div>
              </div>
              <div class="col-auto">
                  <i class="fas fa-shopping-cart fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Productos Despachados</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @orders_dispached_shop %></div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-truck fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Productos Por Despachar</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @orders_not_dispached_shop  %></div>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-shipping-fast fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
    </div>
<div class="row">
    <!-- Area Chart -->
    <div class="card shadow col-md-8">
        <div class="card-body">
          <div class="chart-area">
              <%= line_chart current_user.shop.orders.paid_and_dispached.group_by_day(:created_at).count %>
          </div>
          <hr>
          Cantidad de Ordenes Por dia 
        </div>
      </div>
      <div class="col col-md-4">
          <table class="table">
             <thead class="thead-dark">
                <tr>
                 <th scope="col">Semana</th>
                   <th scope="col">Monto</th>
                </tr>
              </thead>
              <tbody>
               <% @orders.each do |key, value| %>
                  <tr>
                    <th scope="row"><%= key %></th>
                      <th><h4><span class="badge badge-success"><%= value.map{|order| [order.price * order.quantity]}.flatten(2).sum%></span></h4></th>
                    </tr>
                  <% end %>
                </tbody>
            </table>

    </div>
</div>
<br>
<div class="row">
    <!-- Area Chart -->
    <div class="card shadow col-md-8">
        <div class="card-body">
          <div class="chart-area">
              <%= bar_chart current_user.shop.orders.paid_and_dispached.group_by_week(:created_at).count %>
          </div>
          <hr>
          Ordenes Por Semana
        </div>
      </div>
</div>
<br>
</div>

app/views/orders/destroy.js.erb
$('#<%= @order.id%>').fadeOut();
$('#cart').text('<%= current_user.cart.count%>');
$('#total').html("<i class='fas fa-money-bill-alt'></i> <%= @total%>");

app/views/orders/index.html.erb
<br>
<br>
<br>
<div class="container">
<div class="row">
<div class="col col-md-12">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">User ID</th>
      <th>PayID</th>
      <th>Locacion de despacho</th>
      <th scope="col">Productos</th>
      <th scope="col"></th>

    </tr>
  </thead>
  <tbody>
    <% @orders_per_user.each do |key, value| %>
     
    <tr>
      <th scope="row"><span class="badge badge-warning"><%= key %></span></th>
      <th><span class="badge badge-success"><%= value.map{|order| order.billing.code}.first %></span></th>
      <th><span class="text-white bg-dark"><%= value.map{|order| order.billing.address}.first %></span></th>
      <td> 

          <% value.map{|order| [order.product.name,order.quantity]}.each do |product|  %>
        <span class="badge badge-warning"><%= product.first %></span> <span class= "badge badge-info"><%= product.second %></span><br>
        <%end %>
    </td>
    <td><%= link_to "Marcar Como despachado", dispached_order_path(key), method: :patch, class: 'btn btn-warning' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/orders/less_item.js.erb
$('#item_quantity_<%=@order.id%>').html("<%= @order.quantity%>");
$('#total').html("<i class='fas fa-money-bill-alt'></i> <%= @total%>");

app/views/orders/user.html.erb
<br>
<br>
<br>
<div class="container">
                <table id="cart" class="table table-hover table-condensed">
                  <thead>
                    <tr>
                      <th>PayID</th>
                      <th style="width:50%">Producto</th>
                      <th style="width:8%">Cantidad</th>
                      <th style="width:10%">Precio</th>
                       </tr>
                  </thead>
                  <tbody>
        <% @orders_user.each do |order| %>
                        

                    <tr id="<%= order.id%>">
                            <td><span class="badge badge-warning"><%= order.billing.code %></span></td>
                      <td data-th="Product">
                        <div class="row">
                          <div class="col-sm-4 hidden-xs"><%= image_tag(order.product.image.variant(resize: '150x150'),class:"img-responsive") %></div>
                          <div class="col-sm-8">
                            <h6 class="nomargin"><span class="badge badge-success"><%= order.product.name %></span></h6>
                          </div>
                        </div>
                      </td>
                      <td data-th="Quantity">                        
                        <span class="badge badge-warning" id="item_quantity_<%= order.id%>"><%= order.quantity%> </span>
                      </td>
                      <td><%= order.price %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>