config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'locations/find_address'
  resources :categories, only: %i[show] do
    member do
      get :search
    end
  end
  resources :orders, only: %i[index destroy] do
    collection do
      get :cart
      get :user
      get :dashboard
      delete :empty_cart
    end
    member do
      patch :add_item
      patch :less_item
      patch :dispached
    end
  end
  resources :shops do
    collection do
      get :search
      get :cart
    end
    resources :products do
      collection do
        get :search
        get :search_range_price
      end
      resources :orders, only: %i[create]
    end
  end
  resources :billings, only: [] do
    collection do
      post 'pre_pay'
      get 'execute'
    end
  end
  resources :payout_batches, only: %i[create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'locations/find_address'
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :products, through: :category_products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show search]

  def show  
  end

  def search
    @category = Category.find(params[:id])
    parameters = params[:search]
    if parameters.blank?
      @products = @category.products
    elsif parameters.nil?
      @products = @category.products
    else
      @products = @category.products.where('name LIKE ?', "%#{parameters}%")
    end
    respond_to :js
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/search.js.erb
$('#products').html("<%= j render  @products %>")

app/views/categories/show.html.erb
<div class="container">
<h1><span class="badge badge-warning"><%= @category.name %></span></h1>
<div class="row">
      <div class="col-lg-9 col-md-8 col-sm-12 mx-auto text-center">

                <input class="form-control form-control-lg" placeholder="Busca tu Producto" id="search" type="text">
              </div>
            </div>
            <br>
<div class="row" id='products'>
<% @category.products.each do |product| %>
<article class="card card-product" id="<%= product.id%>">
    <div class="card-body">
    <div class="row">
      <aside class="col-sm-3">
        <div class="img-wrap"><a href="<%= shop_product_path(product.shop.id, product)%>"><%= image_tag(product.image.variant(resize: '800x800'),class: "card-img-top") %></a></div>
      </aside> <!-- col.// -->
      <article class="col-sm-6">
          <h4 class="title"><%= product.name %></h4>
          <div class="rating-wrap  mb-2">
            <ul class="rating-stars">
              <li style="width:80%" class="stars-active"> 
                <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                <i class="fa fa-star"></i> 
              </li>
              <li>
                <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
                <i class="fa fa-star"></i> 
              </li>
            </ul>
          </div> <!-- rating-wrap.// -->
          <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, Lorem ipsum dolor sit amet, consectetuer adipiscing elit, Ut wisi enim ad minim veniam </p>
          <dl class="dlist-align">
          </dl>  <!-- item-property-hor .// -->
          <dl class="dlist-align">
              <dt>Categorias</dt>
                <% product.categories.each do |category| %>
                <dd><span class="badge badge-success"><%= category.name %></span></dd>
                <% end %>
                </dl>  <!-- item-property-hor .// -->
            
        
      </article> <!-- col.// -->
      <aside class="col-sm-3 border-left">
        <div class="action-wrap">
          <div class="price-wrap h4">
            <span class="price"><%= product.price %></span>	

          </div> <!-- info-price-detail // -->
          <p class="text-success">Free shipping</p>
          <br>
          <p>
              <% if can? :update, Product %>

              <% else %>
                <% if product.stock == 0 %>
                          <button type="button" class="btn btn-info" name="button">Producto Agotado</button>
                    <%else %>
                      <%= link_to(shop_product_orders_path(product.shop,product),data: {remote: true}, method: :post) do  %>
                                                 <button class="btn btn-primary">Agregar al Carrito <i class="fas fa-shopping-cart"></i></button>

                                                <% end %>
                      <%end%>
              <% end %>
          </p>
        </div> <!-- action-wrap.// -->
      </aside> <!-- col.// -->
    </div> <!-- row.// -->
    </div> <!-- card-body .// -->
  </article> <!-- card product .// -->

<% end %>
</div>
</div>


 <script>
                  $('#search').keyup(function(){
                    $.ajax({
                      type: "GET",
                      url: "<%= search_category_path(@category) %>",
                      data: {search: $('#search').val()},
                      success: function (response) {

                      }
                });
                  });
                </script>